[package]
name = "faas-parallel-example"
version = "0.0.1"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
dslab-faas = { path = "../../crates/dslab-faas" }
clap = { version = "4.1.1", features = ["derive"] }
